---

- name: Install nginx
  sudo: yes
  apt: pkg=nginx state=installed

- name: Stop apache
  sudo: yes
  service: name=apache2 state=stopped

- name: Disable apache
  sudo: yes
  command: update-rc.d apache2 disable removes=/etc/rc5.d/S91apache2

- name: Enable nginx
  sudo: yes
  command: update-rc.d nginx enable creates=/etc/rc5.d/S20nginx

- name: Start nginx
  sudo: yes
  service: name=nginx state=restarted


