---

- include_vars: "{{ansible_distribution}}.yml"

# Use default mongodb

- name: Add APT key
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc id=7F0CEB10
  when: mongodb_package == 'mongodb-org'

- name: Add APT repository
  apt_repository: repo="{{mongodb_repository}}" update_cache=yes
  when: mongodb_package == 'mongodb-org'

- name: Install MongoDB package
  apt: pkg={{mongodb_package}} state=present

- name: Install additional packages
  apt: pkg={{item}}
  with_items: mongodb_additional_packages
