---



# tasks file for roles/ckan


- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - solr-tomcat

# easy packages
- name: Install python packages
  pip: name={{ item }} virtualenv="{{ venvabs }}"
  with_items:
    git+https://github.com/ckan/ckan.git#egg=ckan


- name: Install ckan requirements
  pip: requirements="{{ venvabs }}/src/ckan/requirements.txt" virtualenv="{{ venvabs }}"

- name: Link solr schema
  sudo: yes
  file:
  args:
      src: "{{ venvabs }}/src/ckan/config/solr/schema.xml"
      dest: "/etc/solr/conf/schema.xml"
      state: link
      force: yes

- name: Restart solr
  sudo: yes
  service: name=tomcat6 state=restarted

- name: Create site directory
  file: path="{{ sitedir }}/ckan" state=directory

# - name: Create site
#   command: "{{ venvabs }}/bin/paster make-config ckan {{ sitedir }}/ckan/development.ini"
#   args:
#     creates: "{{ sitedir }}/ckan/development.ini"

- name: Create site
  template: src=development.ini dest="{{ sitedir }}/ckan/development.ini"

- name: Initialize database
  command: "{{ venvabs }}/bin/paster --plugin=ckan db init -c {{ sitedir }}/ckan/development.ini"

- name: Link repoze stuff
  file:
  args:
      src: "{{ venvabs }}/src/ckan/who.ini"
      dest: "{{ sitedir }}/ckan/who.ini"
      state: link



