---
# tasks file for models

- name: Create model directory
  sudo: yes
  file: path="{{ modeldir }}"
  args:
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Download models
  subversion:
  args:
    repo: "{{ item.repo }}"
    dest: "{{ modeldir }}/{{ item.slug }}"
  with_items: models

- name: Fix permissions
  sudo: yes
  file: path="{{ modeldir }}"
  args:
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: yes

- name: Copy supervisor file
  sudo: yes
  template:
  args:
    src: model.conf
    dest: "/etc/supervisor/conf.d/{{ item.model }}.conf"
  with_items: models

- name: Start supervisor
  sudo: yes
  supervisorctl:
  args:
    name: "{{ item.model }}"
    state: started
  with_items: models
  ignore_errors: True

- name: Restart supervisor
  sudo: yes
  supervisorctl:
  args:
    name: "{{ item.model }}"
    state: restarted
  with_items: models
  ignore_errors: True



