---
# tasks file for models

- name: Create model directory
  sudo: yes
  file: path="{{ modeldir }}"
  args:
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Download models
  subversion:
  args:
    repo: "{{ item.repo }}"
    dest: "{{ modeldir }}/{{ item.slug }}"
  with_items:
    - { slug: 2004bay, repo: "https://repos.deltares.nl/repos/ds/trunk/additional/unstruc/test_data/san_francisco/2004bay" }
    - { slug: parallel, repo: "https://repos.deltares.nl/repos/ds/trunk/additional/unstruc/test_data/san_francisco/parallel" }

- name: Fix permissions
  sudo: yes
  file: path="{{ modeldir }}"
  args:
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: yes

- name: Copy supervisor file
  sudo: yes
  template:
  args:
    src: model.conf
    dest: "/etc/supervisor/conf.d/{{ item.model }}.conf"
  with_items:
    - { model: 2004bay, engine: dflowfm,  configfile: "r02b_bay.mdu", port: 5600 }
    - { model: parallel, engine: dflowfm,  configfile: "r07e_bay.mdu", port: 5900 }


- name: Start supervisor
  sudo: yes
  supervisorctl:
  args:
    name: "{{ item.model }}"
    state: started
  with_items:
    - { model: 2004bay, engine: dflowfm,  configfile: "r02b_bay.mdu", port: 5600 }
    - { model: parallel, engine: dflowfm,  configfile: "r07e_bay.mdu", port: 5900 }
  ignore_errors: True

- name: Restart supervisor
  sudo: yes
  supervisorctl:
  args:
    name: "{{ item.model }}"
    state: restarted
  with_items:
    - { model: 2004bay, engine: dflowfm,  configfile: "r02b_bay.mdu", port: 5600 }
    - { model: parallel, engine: dflowfm,  configfile: "r07e_bay.mdu", port: 5900 }
  ignore_errors: True



