---

- name: Install python and virtualenv
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev

- name: Download OpenEarthTools package
  subversion: repo=https://svn.oss.deltares.nl/repos/openearthtools/trunk/python/OpenEarthTools dest=~/src/OpenEarthTools username=baart_f
- name: Download OpenEarthTools wps processes
  subversion: repo=https://svn.oss.deltares.nl/repos/openearthtools/trunk/python/applications/wps dest=~/src/wps username=baart_f

- name: Download PyWPS
  git: repo=https://www.github.com/geopython/PyWPS.git  dest=~/src/PyWPS

- name: Make WPS output directory
  file:
  args:
    path: "{{ wps_local_output }}"
    state: directory
# easy packages
- name: Install python packages
  pip: name={{ item }}
  args:
    virtualenv: "{{ venvabs }}"
  with_items:
    - shapely
    - gunicorn
    - Paste
    - PasteDeploy
    - waitress
    - couchdb
    - python-dateutil
    - pytz
    - lxml
    # - netCDF4

# difficult packages
- name: Install PyWPS
  pip: name=~/src/PyWPS virtualenv={{ venvabs }} extra_args=-e
- name: Install OpenEarth
  pip: name=~/src/OpenEarthTools virtualenv={{ venvabs }} extra_args=-e

# tasks file for wps
- name: Stop supervisor
  sudo: yes
  service: name=supervisor state=stopped


- name: Copy supervisor process
  sudo: yes
  template:
  args:
    src: supervisor_wps.conf
    dest: ~/etc/supervisor/conf.d/pywps.conf

- name: Copy pywps configuration
  template:
  args:
    src: pywps_wps.cfg
    dest: ~/pywps.cfg


