---

- name: Default setup
  hosts: all
  vars:
    venv: main
  roles:
    - { role: system, tags: [ 'system' ]}
    - { role: python, tags: [ 'python' ]}
    - { role: swap, tags: [ 'swap' ] }

- name: Install WPS
  hosts: wps
  vars:
    venv: main
  roles:
    - { role: nginx, tags: [ 'nginx' ] }
    - { role: couchdb, tags: [ 'couchdb' ] }
    - { role: wps, tags: [ 'wps' ] }

- name: Lizard viewer
  hosts: lizard
  vars:
    venv: main
  roles:
    - { role: nginx, tags: [ 'nginx' ] }
    - { role: lizard, tags: [ 'lizard' ] }
    - { role: netcdf, tags: [ 'netcdf' ] } # custom netCDF4 version because 4.1.1 is broken
    - { role: vectors, tags: [ 'vectors' ] }

- name: Install Model Message service
  hosts: mmi
  vars:
    venv: main
  roles:
    - { role: mmi, tags: [ 'mmi' ] }
    - { role: engines, tags: [ 'engines' ] }
    - { role: models, tags: [ 'models' ] }
    - { role: nodejs, tags: ['nodejs']}
    - { role: nginx, tags: [ 'nginx' ] }
    - { role: threedi-unstruc, tags: ['threedi-unstruc']}

- name: Install CKAN
  hosts: ckan
  vars:
    venv: main
    databases:
      - { name: ckan_default, owner: ckan_default, encoding: utf-8 }
  roles:
    - { role: postgis, tags: [ 'postgis' ] }
    - { role: ckan, tags: [ 'ckan' ] }


