---

- name: Default setup
  hosts: all
  roles:
    - { role: system, tags: [ 'system' ]}
    - { role: python, tags: [ 'python' ]}

- name: Install WPS
  hosts: default
  roles:
    - { role: couchdb, tags: [ 'couchdb' ] }

# - name: Install Model Message service
#   hosts: default
#   roles:
#     - { role: mmi, tags: [ 'mmi' ] }


