---

- name: Default setup
  hosts: all
  vars:
    venv: main
  roles:
    - { role: system, tags: [ 'system' ]}
    - { role: python, tags: [ 'python' ]}

- name: Install WPS
  hosts: wps
  vars:
    venv: main
  roles:
    - { role: nginx, tags: [ 'nginx' ] }
    - { role: couchdb, tags: [ 'couchdb' ] }
    - { role: wps, tags: [ 'wps' ] }

- name: Install Model Message service
  hosts: mmi
  vars:
    venv: main
  roles:
    - { role: swap, tags: [ 'swap' ] }
    - { role: mmi, tags: [ 'mmi' ] }
    - { role: engines, tags: [ 'engines' ] }
    - { role: models, tags: [ 'models' ] }


- name: Install CKAN
  hosts: ckan
  vars:
    venv: main
    databases:
      - { name: ckan_default, owner: ckan_default, encoding: utf-8 }
  roles:
    - { role: swap, tags: [ 'swap' ] }
    - { role: postgis, tags: [ 'postgis' ] }
    - { role: ckan, tags: [ 'ckan' ] }


