---

- name: Default setup
  hosts: all
  vars:
    venv: main
  roles:
    - { role: system, tags: [ 'system' ]}
    - { role: python, tags: [ 'python' ]}

- name: Install WPS
  hosts: default
  vars:
    venv: main
  roles:
    - { role: nginx, tags: [ 'nginx' ] }
    - { role: couchdb, tags: [ 'couchdb' ] }
    - { role: wps, tags: [ 'wps' ] }

- name: Install Model Message service
  hosts: default
  vars:
    venv: main
  roles:
    - { role: swap, tags: [ 'swap' ] }
    - { role: mmi, tags: [ 'mmi' ] }
    - { role: engines, tags: [ 'engines' ] }
    - { role: models, tags: [ 'models' ] }


