---

- name: Default setup
  hosts: all
  vars:
    venv: main
  roles:

- name: Docker
  hosts: emodnet
  vars:
    venv: main
    project: emodnet
  roles:
    - { role: docker, tags: [ 'docker' ] }

- name: Install WPS
  hosts: emodnet-docker
  vars:
    venv: main
  roles:
    - { role: python, tags: [ 'python' ]}
    - { role: wps, tags: [ 'wps' ] }



