---

- name: Default setup
  hosts: all
  vars:
    venv: main
  roles:
    - { role: system, tags: [ 'system' ]}
    - { role: swap, tags: [ 'swap' ] }
    - { role: python, tags: [ 'python' ]}

- name: Install WPS
  hosts: wps
  vars:
    venv: main
  roles:
    - role: nginx
      sudo: yes
      tags: [ 'nginx' ]
      nginx_sites:
        default:
          - listen 80 default_server
          - listen [::]:80 default_server ipv6only=on
          - location / { try_files $uri $uri/ =404; }
          - root /var/www/wps
          - index index.html index.htm
          - server_name wps.openearth.nl
          - server_name localhost
          - location /couchdb  {
             proxy_pass http://couchdb;
             rewrite /couchdb/(.*) /$1 break;
             }
          - location /wps {
             proxy_pass http://wps;
             rewrite /wps/(.*) /$1 break;
             add_header Access-Control-Allow-Origin *;
             add_header Access-Control-Allow-Headers X-Requested-With;
             }
          - location /output {
             root {{ wps_output }}
             add_header Access-Control-Allow-Origin *;
             add_header Access-Control-Allow-Headers X-Requested-With;
             }
      nginx_configs:
        proxy:
          - proxy_redirect off
          - proxy_buffering off
          - proxy_set_header Host $host
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for

        upstream:
          - upstream couchdb {
              server 127.0.0.1:5984;
            }
          - upstream wps {
              server 127.0.0.1:6543;
            }

    - { role: couchdb, tags: [ 'couchdb' ] }
    - { role: wps, tags: [ 'wps' ] }



- name: Lizard viewer
  hosts: lizard
  vars:
    venv: main
  roles:
    - { role: nginx_wps, tags: [ 'nginx_wps' ] }
    - { role: lizard, tags: [ 'lizard' ] }
    - { role: netcdf, tags: [ 'netcdf' ] } # custom netCDF4 version because 4.1.1 is broken
    - { role: vectors, tags: [ 'vectors' ] }

- name: Install Model Message service
  hosts: mmi
  vars:
    venv: main
  roles:
    - { role: mmi, tags: [ 'mmi' ] }
    - { role: engines, tags: [ 'engines' ] }
    - { role: models, tags: [ 'models' ] }
    - { role: nodejs, tags: ['nodejs']}
    - { role: nginx_wps, tags: [ 'nginx_wps' ] }
    - { role: threedi-unstruc, tags: ['threedi-unstruc']}

- name: Install CKAN
  hosts: ckan
  vars:
    venv: main
    databases:
      - { name: ckan_default, owner: ckan_default, encoding: utf-8 }
  roles:
    - { role: postgis, tags: [ 'postgis' ] }
    - { role: ckan, tags: [ 'ckan' ] }

- name: Install SWAPP
  hosts: swapp
  vars:
    venv: main
  roles:
    - { role: swap, tags: [ 'swap' ] }
    - role: nginx
      sudo: yes
      tags: [ 'nginx' ]
      nginx_sites:
        default:
          - listen 80
          - location / { try_files $uri $uri/ /index.html; }
          - location /db  {
             proxy_pass http://mongodb;
             rewrite /db/(.*) /$1 break;
            }
      nginx_configs:
        proxy:
          - proxy_redirect off
          - proxy_buffering off
          - proxy_set_header Host $host
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
        upstream:
          - upstream mongodb {
              server 127.0.0.1:6011;
            }
    - { role: mongodb, tags: [ 'mongodb' ] }
    - { role: kule, tags: [ 'kule' ] }



