---

- name: Default setup
  hosts: all
  vars:
    venv: main
  roles:
    - { role: python, tags: [ 'python' ]}
    - { role: swap, tags: [ 'swap' ] }

- name: Install WPS
  hosts: emodnet
  vars:
    venv: main
  roles:
    - { role: wps, tags: [ 'wps' ] }



