
---

- name: Swap on?
  shell: swapon -s | grep -q swap.1
  register: swapoff
  ignore_errors: true

- name: Swap is on
  command: echo swap is on
  when: not swapoff

- name: Swap is off
  command: echo swap is off
  when: swapoff

- name: Create swap file
  sudo: yes
  command: /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048 creates=/var/swap.1
  when: swapoff

- name: Format swap file
  sudo: yes
  shell: /sbin/mkswap /var/swap.1
  when: swapoff

- name: Use swap file
  sudo: yes
  # Check if we can find swap in swap.1, if not turn it on
  shell: /sbin/swapon /var/swap.1
  when: swapoff
