
---

- name: Create swap file
  sudo: yes
  shell: swapon -s | grep -q swap.1 || /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048 creates=/var/swap.1

- name: Format swap file
  sudo: yes
  shell: swapon -s | grep -q swap.1 || /sbin/mkswap /var/swap.1

- name: Use swap file
  sudo: yes
  # Check if we can find swap in swap.1, if not turn it on
  shell: swapon -s | grep -q swap.1 || /sbin/swapon /var/swap.1
