---
# tasks file for couchdb

- name: Install CouchDB from package manager
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
    - couchdb

# TODO: add some conditions

- name: Stop CouchDB
  sudo: True
  service: name=couchdb enabled=yes state=stopped

- name: Copy the local ini file
  sudo: True
  copy:
    src: local.ini
    dest: "{{ couchdb_dir }}/local.ini"
    owner: couchdb
    group: couchdb
    mode: 0640

- name: Start CouchDB
  sudo: True
  service: name=couchdb enabled=yes state=restarted

# There must be an easier way to do this...
- name: Copy the views
  copy:
    src: views.json
    dest: /tmp/views.json

- name: Copy views to variable
  shell: cat /tmp/views.json
  register: views

- name: Delay, wait for the server to be active...
  wait_for: port=5984 state=present

- name: Check if couchdb is up
  uri: url=http://localhost:5984

- name: Create database
  uri: url=http://localhost:5984/wps
       method=PUT
       status_code=200,201,412

# if we get 412, the file already exists
- name: Create views in database
  shell: curl -sw "%{http_code}\\n" -X PUT http://localhost:5984/wps/_design/views -d @/tmp/views.json
  register: status

# - name: Delete views file
#   file:
#     dest: /tmp/views.json
#     state: absent

