---
# tasks file for dflowfm


- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - gfortran
    - gcc
    - g++
    - flex
    - bison
    - libnetcdff5
    - libnetcdf-dev
    - build-essential
    - autoconf
    - automake
    - libtool
    - libopenmpi-dev
    - openmpi-bin

- name: Check for DflowFM source
  command: test -d "/home/{{ ansible_ssh_user }}/src/unstruc"
  register: fm_source
  ignore_errors: true

- name: Download DflowFM
  subversion: repo=https://repos.deltares.nl/repos/ds/trunk/additional/unstruc
  args:
    dest: "/home/{{ ansible_ssh_user }}/src/unstruc"
    username: baart_f
  when: fm_source|failed

- name: Autogen
  command: ./autogen.sh
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/unstruc"
    creates: "/home/{{ ansible_ssh_user }}/src/unstruc/Makefile.in"


# Custom FCFLAGS because /usr/include is not in default path
- name: Configure
  shell: FCFLAGS="-I/usr/include -g -O2" ./configure --with-netcdf
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/unstruc"
    creates: "/home/{{ ansible_ssh_user }}/src/unstruc/Makefile"


- name: Make
  command: make
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/unstruc"
    creates: "/home/{{ ansible_ssh_user }}/src/unstruc/src/dflowfm"
- name: Make install
  sudo: yes
  command: make install
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/unstruc"
    creates: "/usr/local/bin/dflowfm"



- name: Check for Delft3D source
  command: test -d "/home/{{ ansible_ssh_user }}/src/delft3d"
  register: delft3d_source
  ignore_errors: true

- name: Download Delft3D
  subversion: repo=https://svn.oss.deltares.nl/repos/delft3d/branches/research/Deltares/20140512_Irv
  args:
    dest: "/home/{{ ansible_ssh_user }}/src/delft3d"
    username: baart_f
  when: delft3d_source|failed

- name: Autogen
  command: ./autogen.sh
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/delft3d"
    creates: "/home/{{ ansible_ssh_user }}/src/delft3d/Makefile.in"

# Custom FCFLAGS because /usr/include is not in default path
- name: Configure
  shell: FCFLAGS="-I/usr/include -g -O2" ./configure  --with-mpi
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/delft3d"
    creates: "/home/{{ ansible_ssh_user }}/src/delft3d/Makefile"

- name: Make delft3d
  command: make
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/delft3d"

- name: Make install
  sudo: yes
  command: make install
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/delft3d"
    creates: "/usr/local/bin/d_hydro.exe"