---
# tasks file for kule

# Install system version
- name: Install extra python packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - python-pymongo

# or user version
- name: Install python packages
  pip: name={{ item }} virtualenv="{{ venvabs }}"
  with_items:
    - pymongo
    - git+https://github.com/SiggyF/kule@swapp-0.1#egg=kule

- name: Stop supervisor
  sudo: yes
  service: name=supervisor state=stopped

- name: Copy supervisor process
  sudo: yes
  template:
  args:
    src: supervisor_kule.conf
    dest: /etc/supervisor/conf.d/kule.conf

- name: Start supervisor
  sudo: yes
  service: name=supervisor state=started
