---
# tasks file for lastools

# install external dependencies needed for lastools
- name: install git
  apt: name=git state=latest
  sudo: yes

- name: install libgdal-dev
  apt: name=libgdal-dev state=latest
  sudo: yes

- name: install gdal-bin
  apt: name=gdal-bin state=latest
  sudo: yes  

- name: install python gdal
  apt: name=python-gdal state=latest
  sudo: yes

- name: install geotiff library
  apt: name=libgeotiff-dev state=latest
  sudo: yes

- name: install aclocal
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - build-essential
    - autoconf
    - automake
    - libtool

- name: Install cmake
  apt: pkg={{ item }} state=present update_cache=yes
  tags: package
  with_items:
   - cmake
   - cmake-curses-gui
  sudo: yes

- name: install gcc
  apt: name=gcc state=installed
  sudo: yes

- name: install libproj-dev for Cartographic projection library (development files)
  apt: name=libproj-dev state=latest
  sudo: yes

- name: install libboost
  apt: name=libboost-all-dev state=latest
  sudo: yes

# Compile laszip for compression suport.
- name: create source directory for laszip
  file: dest=~/src/laszip state=directory

- name: checkout laszip git
  git: repo=https://github.com/LASzip/LASzip
       dest=~/src/laszip

- name: Autogen laszip
  command: ./autogen.sh
  args:
    chdir: ~/src/laszip
    creates: ~/src/laszip/Makefile.in

- name: Configure laszip
  command: ./configure
  args:
    chdir: ~/src/laszip
    creates: ~/src/laszip/Makefile

- name: Make laszip
  command: /usr/bin/make
  args:
    chdir: ~/src/laszip

- name: Make install laszip
  command: make install
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/laszip"
  sudo: yes

# Compile liblas
- name: create source directory for liblas
  file: dest=~/src/liblas state=directory

- name: checkout liblas git
  git: repo=https://github.com/libLAS/libLAS
       dest=~/src/liblas version=1.8.0

- name: prepare a build directory
  file: path=~/src/liblas/build state=directory

- name: configure base library
  command: cmake -G "Unix Makefiles" -DWITH_LASZIP=ON -DWITH_GEOTIFF=ON -DWITH_GDAL=ON ~/src/liblas/
  args:
    chdir: ~/src/liblas/build

- name: Build liblas library
  command: /usr/bin/make
  args:
    chdir: ~/src/liblas/build

- name: Install liblas
  command: /usr/bin/make install
  args:
    chdir: "/home/{{ ansible_ssh_user }}/src/liblas/build"
  sudo: yes

- name: run ldconfig to update systemlibraries
  action: command /sbin/ldconfig
  sudo: yes

# Compile lastools

- name: checkout lastools git
  git: repo=https://github.com/LAStools/LAStools
       dest=~/src/lastools

- name: build lastools
  command: /usr/bin/make
  args:
    chdir: ~/src/lastools
    creates: ~/src/lastools/src/las2las

# Copy lasmerge from lastools to /usr/local/bin. This is a temporary solution!!!
# TODO makefile aanpassen with install option so only lasmerge will be added to /usr/local/bin

- name: copy lasmerge to /usr/local/bin
  copy: src=/home/{{ ansible_ssh_user }}/src/lastools/bin/lasmerge dest=/usr/local/bin/ mode="0755"
  sudo: yes
