# tasks file for postgresql

- name: Install PostgreSQL
  sudo: yes
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - "postgresql-{{ postgresql_version }}"
    - "postgresql-client-{{ postgresql_version }}"
    - "postgresql-contrib"
    - "python-psycopg2"
    - "postgis"


- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

# Just give all rights
- name: Create users
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name="{{ item.owner }}"
    state=present
    role_attr_flags="SUPERUSER"
  with_items: databases
  when: databases | length > 0

# Make database
- name: Create databases
  sudo: yes
  sudo_user: postgres
  postgresql_db: name="{{ item.name }}"
                 encoding="{{ item.encoding }}"
                 owner="{{ item.owner }}"
  with_items: databases
  when: databases | length > 0
