---
# tasks file for threedi-unstruc
- name: Threedi unstruc git repository
  git:
  args:
    repo: https://github.com/openearth/threedi-unstruc
    dest: src/threedi-unstruc

- name: Ruby-sass
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby-sass

- name: Install gulp
  npm: name=gulp global=yes
- name: Install bower
  npm: name=bower global=yes

- name: Install local gulp
  npm: name=gulp path=/home/ubuntu/src/threedi-unstruc state=latest
- name: Install local bower
  npm: name=gulp path=/home/ubuntu/src/threedi-unstruc state=latest
- name: Install local files
  npm: path=/home/ubuntu/src/threedi-unstruc state=latest

- name: Download bower stuff
  shell: /home/ubuntu/.node/bin/bower install
  args:
    chdir: ~/src/threedi-unstruc

- name: Build website
  shell: /home/ubuntu/.node/bin/gulp build
  args:
    chdir: ~/src/threedi-unstruc