---
# tasks file for threedi-unstruc
- name: Threedi unstruc git repository
  git:
  args:
    repo: https://github.com/openearth/threedi-unstruc
    dest: src/threedi-unstruc

- name: Ruby-sass
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby-sass

- name: Install gulp
  npm: name=gulp global=yes
- name: Install bower
  npm: name=bower global=yes

- name: Install local gulp
  npm:
  args:
    name: gulp
    path: "/home/{{ ansible_ssh_user}}/src/threedi-unstruc"
    state: latest

- name: Install local bower
  npm: name=gulp path=/home/{{ ansible_ssh_user}}/src/threedi-unstruc state=latest
- name: Install local files
  npm: path=/home/{{ ansible_ssh_user}}/src/threedi-unstruc state=latest

- name: Download bower stuff
  shell: /home/{{ ansible_ssh_user}}/.node/bin/bower install
  args:
    chdir: ~/src/threedi-unstruc

- name: Build website
  shell: /home/{{ ansible_ssh_user}}/.node/bin/gulp build
  args:
    chdir: ~/src/threedi-unstruc

- name: Copy nginx threedi unstruc configuration
  sudo: yes
  template:
  args:
    src: nginx_threedi-unstruc.conf
    dest: /etc/nginx/sites-available/threedi-unstruc.conf

- name: Remove default site
  sudo: yes
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Enable threedi site
  sudo: yes
  file:
  args:
    src: /etc/nginx/sites-available/threedi-unstruc.conf
    dest: /etc/nginx/sites-enabled/threedi-unstruc.conf
    state: link

- name: Restart threedi
  sudo: yes
  service:
  args:
    name: nginx
    state: restarted
