---
# tasks file for mmi

- name: Install python packages
  pip: name={{ item }} virtualenv={{ venvabs }}
  with_items:
    - tornado


- name: BMI checked out
  command: test -d ~/src/bmi-python
  register: bmi_missing
  ignore_errors: true

- name: MMI checked out
  command: test -d ~/src/mmi-python
  register: mmi_missing
  ignore_errors: true

- name: Download git repos
  git: repo=https://github.com/openearth/bmi-python.git dest=~/src/bmi-python
  when: bmi_missing
- name: Download git repos
  git: repo=https://github.com/openearth/mmi-python.git dest=~/src/mmi-python
  when: mmi_missing

- name: Install BMI
  pip: name="~/src/bmi-python" virtualenv={{ venvabs }}
- name: Install MMI
  pip: name="~/src/mmi-python" virtualenv={{ venvabs }}

