---
# tasks file for mmi

- name: Install python packages
  pip: name={{ item }} virtualenv={{ venvabs }}
  with_items:
    - tornado

- name: Download git repos
  git: repo=https://github.com/openearth/bmi-python.git
       dest=~/src/bmi-python
       update=no
- name: Download git repos
  git: repo=https://github.com/openearth/mmi-python.git
       dest=~/src/mmi-python
       update=no

- name: Update git repos
  git: repo=https://github.com/openearth/bmi-python.git
       dest=~/src/bmi-python
       update=yes

- name: Update git repos
  git: repo=https://github.com/openearth/mmi-python.git
       dest=~/src/mmi-python
       update=yes

- name: Install BMI
  pip: name="~/src/bmi-python" virtualenv={{ venvabs }} extra_args=-e
- name: Install MMI
  pip: name="~/src/mmi-python" virtualenv={{ venvabs }} extra_args=-e


- name: Copy supervisor file
  sudo: yes
  template:
  args:
    src: tracker.conf
    dest: "/etc/supervisor/conf.d/tracker.conf"

- name: Reload supervisor
  sudo: yes
  supervisorctl: name=tracker state=restarted
